stages:
  - build
  - deploy

build:
  stage: build
  image: node:12.19.0
  only:
    - dev
    - master
  script:
    - '[ "$CI_COMMIT_BRANCH" == "master" ] && ENV="$ENV_PRODUCTION" || ENV="$ENV_STAGING"'
    - '[ "$CI_COMMIT_BRANCH" == "master" ] && APP="app-production.yaml" || APP="app-staging.yaml"'
    - echo "$ENV" > .env.local
    - yarn install --cache-folder .yarn
    - yarn build
    - cp $APP app.yaml
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - .yarn
      - .next/cache/
  artifacts:
    paths:
      - .next
      - public
      - .env.local
      - app.yaml
      - package.json

deploy:
  stage: deploy
  image: google/cloud-sdk:slim
  only:
    - dev
    - master
  script:
    - echo "$SERVICE_ACCOUNT_KEY" > key.json
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud app deploy app.yaml --quiet --project=chula-chana
