env: standard
runtime: nodejs12
service: staging

handlers:
  - url: /.*
    secure: always
    script: auto

vpc_access_connector:
  name: projects/chula-chana/locations/asia-southeast2/connectors/chana-connector
