version: "3.3"

services:
  app:
    container_name: chulachana_web
    build: .
    ports:
      - "8080:8080"
    links:
      - redis
  redis:
    image: redis
    volumes:
      - redis-data:/data

volumes:
  redis-data: {}

networks:
  default:
     external:
        name: nginx_proxy_manager

