version: '3.3'

services:
  app:
    container_name: chulachana_web
    build: .
    ports:
      - '8080:8080'
    links:
      - postgres
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: x4W4PsQpUT6Bwjm7mEuW7KcFZf4pgb8x
      POSTGRES_DB: chulachana
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}

networks:
  default:
    external:
      name: nginx_proxy_manager
