version: '3'

services:
  app:
    container_name: app-container
    image: node:14.14.0
    environment:
      INFLUX_URL: ${DB_URL}
      INFLUX_ORG: ${DB_ORG}
      INFLUX_USERNAME: ${DB_ADMIN_USER}
      INFLUX_PASSWORD: ${DB_ADMIN_PASS}
      INFLUX_TOKEN: ${DB_TOKEN}
      INFLUX_BUCKET_PREFIX: ${DB_BUCKET_PREFIX}
      TZ: Asia/Bangkok
    ports:
      - 3000:3000
    volumes:
      - .:/app/src
    working_dir: /app/src
    command: yarn dev
    depends_on:
      - influxdb
  influxdb:
    container_name: influxdb-container
    image: quay.io/influxdb/influxdb:2.0.0-rc
    environment:
      TZ: Asia/Bangkok
    ports:
      - 8086:8086
    volumes:
      - ./db_volumes:/var/lib/influxdb2
    command: bash -c 'influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store bolt && influx setup -b ${DB_INIT_BUCKET} -f -o ${DB_ORG} -p ${DB_ADMIN_PASS} -u ${DB_ADMIN_USER} -t ${DB_TOKEN}'

# docker exec -it influxdb-container influx setup -b initial_bucket -f -o isdsgcu -p admin123 -u admin -t ABCDEFGHIJKLMNOPQRSTUVWXYZ-1234567890_abcdefghijklmnopqrstuvwxyz