version: '3.7'

services:
  app:
    container_name: chulachana
    build: .
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - '8080:8080'
    networks:
      - database
      - nginx_proxy_manager

networks:
  database:
    external: true
    driver: overlay
    name: database
  nginx_proxy_manager:
    external: true
    driver: overlay
    name: nginx_proxy_manager
