name: Log current user count to DB

on:
  schedule:
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger log API
        run: curl -X POST -d {} https://cucheck.in/api/log/usercount
